version: 1.0.{build}
image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
  mkdir build
  
  cd build
  
  cmake c:\projects\source -G "Visual Studio 15"
  
  cmake --build . --config "Debug"
platform: x64
configuration: Debug
build:
  parallel: true
verbosity: normal
artifacts:
  path: E79.zip
deploy:
  provider: GitHub
  artifact: E79.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
